[project]
name = "taxverify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "email-validator>=2.3.0",
    "fastapi>=0.142.4",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.6",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "psycopg[binary]>=3.3.6",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.4",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.1.4",
    "uvicorn[standard]>=0.54.0",
]
