"""create initial taxverify tables

Revision ID: 4fff06730c82
Revises: 
Create Date: 2026-10-08 03:44:32.982066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fff06730c82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_pan'), 'clients', ['pan'], unique=True)
    op.create_table('tax_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'financial_year', name='uq_client_financial_year')
    )
    op.create_index(op.f('ix_tax_cases_client_id'), 'tax_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_tax_cases_id'), 'tax_cases', ['id'], unique=False)
    op.create_table('broker_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_case_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('format_version', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('validation_message', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tax_case_id'], ['tax_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_reports_file_hash'), 'broker_reports', ['file_hash'], unique=False)
    op.create_index(op.f('ix_broker_reports_id'), 'broker_reports', ['id'], unique=False)
    op.create_index(op.f('ix_broker_reports_tax_case_id'), 'broker_reports', ['tax_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_reports_tax_case_id'), table_name='broker_reports')
    op.drop_index(op.f('ix_broker_reports_id'), table_name='broker_reports')
    op.drop_index(op.f('ix_broker_reports_file_hash'), table_name='broker_reports')
    op.drop_table('broker_reports')
    op.drop_index(op.f('ix_tax_cases_id'), table_name='tax_cases')
    op.drop_index(op.f('ix_tax_cases_client_id'), table_name='tax_cases')
    op.drop_table('tax_cases')
    op.drop_index(op.f('ix_clients_pan'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
