"""add groww report audit models

Revision ID: c81cb8f04ab7
Revises: 4fff06730c82
Create Date: 2026-10-08 04:40:25.990460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81cb8f04ab7'
down_revision: Union[str, Sequence[str], None] = '4fff06730c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('source_cell', sa.String(length=50), nullable=True),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('derivation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['broker_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_metrics_id'), 'report_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_report_metrics_metric_key'), 'report_metrics', ['metric_key'], unique=False)
    op.create_index(op.f('ix_report_metrics_report_id'), 'report_metrics', ['report_id'], unique=False)
    op.create_table('report_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=150), nullable=False),
    sa.Column('reported_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('calculated_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['broker_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reconciliations_id'), 'report_reconciliations', ['id'], unique=False)
    op.create_index(op.f('ix_report_reconciliations_report_id'), 'report_reconciliations', ['report_id'], unique=False)
    op.add_column('broker_reports', sa.Column('broker_client_name', sa.String(length=200), nullable=True))
    op.add_column('broker_reports', sa.Column('broker_client_code', sa.String(length=100), nullable=True))
    op.add_column('broker_reports', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('broker_reports', sa.Column('period_end', sa.Date(), nullable=True))
    op.alter_column('broker_reports', 'stored_filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('broker_reports', 'validation_message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_broker_reports_broker_client_code'), 'broker_reports', ['broker_client_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_reports_broker_client_code'), table_name='broker_reports')
    op.alter_column('broker_reports', 'validation_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('broker_reports', 'stored_filename',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('broker_reports', 'period_end')
    op.drop_column('broker_reports', 'period_start')
    op.drop_column('broker_reports', 'broker_client_code')
    op.drop_column('broker_reports', 'broker_client_name')
    op.drop_index(op.f('ix_report_reconciliations_report_id'), table_name='report_reconciliations')
    op.drop_index(op.f('ix_report_reconciliations_id'), table_name='report_reconciliations')
    op.drop_table('report_reconciliations')
    op.drop_index(op.f('ix_report_metrics_report_id'), table_name='report_metrics')
    op.drop_index(op.f('ix_report_metrics_metric_key'), table_name='report_metrics')
    op.drop_index(op.f('ix_report_metrics_id'), table_name='report_metrics')
    op.drop_table('report_metrics')
    # ### end Alembic commands ###
